#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service() {
	local enabled
	local brightness
	
	config_load screen_brightness
	config_get enabled config enabled 0
	config_get brightness config brightness 128
	
	if [ "$enabled" = "1" ]; then
		/bin/set-xgp-screen-brightness $brightness
	fi
}

stop_service() {
	return 0
}

restart() {
	start
}